#%RAML 1.0 Trait

      body:
        application/json:
          type: db-type.lib
          example: !include ../Example/post-requestBody.json
      responses:
        201:
          body:
            application/json:
              example: !include ../Example/post-responseBody.json